---
title: "Identifiability in RCT"
author: "Fan Yin"
date: '2021-02-15T21:13:14-05:00'
output: html_document
bibliography: sample.bib
categories: Causal Inference
tags: ["Causal Inference"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_CHTML.js"></script>

In this blog, I shall summarize my learning about why and how we are able to identify the average treatment effect from randomized controlled trials (RCT). 

Under the potential outcome framework \citep{rubin1974estimating}, we have $n$ i.i.d samples $(X_{i}, W_{i}, Y_{i}(1), Y_{i}(0)) \in \mathbb{R}^{d} \times \{0, 1\} \times \mathbb{R} \times \mathbb{R}$, with the individual causal effect being defined as 

$$ \Delta_{i} \equiv Y_{i}(1) - Y_{i}(0) $$

where $Y_{i}(1)$ denotes the outcome of individual $i$ \emph{if} it were to receive the treatment, $Y_{i}(0)$ denotes the outcome of individual $i$ \emph{if} it were NOT to receive the treatment. Here, we focus on the scenario under which each individual either receives or not receives the treatment ($W_{i} = 0, 1$), and also assume that the treatment is stable across individuals and the individuals do not interfere with each other. 

The fundamental challenge here is that we have a missing data problem, that is, $\Delta_{i}$ is never observed, though we might imagine a \emph{counterfactual} world where everything is the same except the cause. The implication here is that we cannot estimate the individual causal effect of the treatment, but we might hope to estimate the average treatment effect (ATE)

$$ \tau \equiv \mathbb{E}[\Delta_{i}] = \mathbb{E}[Y_{i}(1) - Y_{i}(0)] $$

Under randomized controlled trials (RCT), we have the following assumptions

* Consistency: $Y_{i} = W_{i} Y_{i}(1) + (1 - W_{i}) Y_{i}(0)$.
* Random treatment assignment: $W_{i}$ is independent of $(Y_{i}(1), Y_{i}(0), X_{i})$.

therefore, we have

$$ \tau \equiv \mathbb{E}[\Delta_{i}] = \mathbb{E}[Y_{i}(1) - Y_{i}(0)] \stackrel{(1)}{=} \mathbb{E}[Y_{i}(1) | W_{i} = 1] - \mathbb{E}[Y_{i}(0) | W_{i} = 0] \stackrel{(2)}{=} \mathbb{E}[Y_{i} | W_{i} = 1] - \mathbb{E}[Y_{i} | W_{i} = 0] $$

where (1) is based on the assumption of random treatment assignment, and (2) is based on the assumption of consistency. Therefore, we can estimate $\tau$ by the estimator below

$$ \hat{\tau} = \frac{1}{n_{1}} \sum_{W_{i}=1} Y_{i} -  \frac{1}{n_{0}} \sum_{W_{i}=0} Y_{i}$$



