baseURL: https://thestatsdude.netlify.app/
title: Fan Yin
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  author: Fan Yin
  description: Data Scientist / Statistician 
  menu_item_separator: ' - '
  avatar: /static/avatar.jpg
  social:
    - icon: github
      name: Github
      url: https://github.com/fyin-stats
    - icon: linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/fan-y-a7973689/
